let fs = require("fs"),
    xUtil = require("./src/xUtil"),
    xFile = require("./src/xFile"),
    xNumber = require("./src/xNumber"),
    xHtml = require("./src/xHtml"),
    xTool = {
        typeof: xUtil.typeof,
        is: xUtil.is,
        flattenArray: xUtil.flattenArray,
        distinctArray: xUtil.distinctArray,
        getArgs: xUtil.getArgs,
        range: xUtil.range,
        prepareDir: xFile.prepareDir,
        readDir: xFile.readDir,
        readFile: xFile.readFile,
        existFile: xFile.existFile,
        existDir: xFile.existDir,
        saveFile: xFile.saveFile,
        removeFile: xFile.removeFile,
        scanFile: xFile.scanFile,
        scanListFile: xFile.scanListFile,
        replaceFile: xFile.replaceFile,
        tolerant: xNumber.tolerant,
        numberChnToBig: xNumber.numberChnToBig,
        numberChnToSmall: xNumber.numberChnToSmall,
        numberAri2Chn: xNumber.numberAri2Chn,
        numberChn2Ari: xNumber.numberChn2Ari,
        isLegalChnNum: xNumber.isLegalChnNum,
        numberAri2Roman: xNumber.numberAri2Roman,
        numberRoman2Ari: xNumber.numberRoman2Ari,
        decodeHtml: xHtml.decodeHtml
    };

module.exports = xTool;